spring:
  profiles:
    active: dev

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization
  secret: discount-portal-secret
  expiration: 604800
  tokenHead: Bearer

secure:
  ignored:
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/show/**
      - /plaza/show/**
      - /aliyun/oss/callback

aliyun:
  oss:
    endpoint: shanghai # oss对外服务的访问域名
    accessKeyId: accessKeyI # 访问身份验证中用到用户标识
    accessKeySecret: secret # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: jasonper-soft # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:8085/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: avatar/ # 上传文件夹路径前缀

redis:
  database: ns_discount
  key:
    authCode: 'ums:authCode'
    player: 'ums:player'
  expire:
    authCode: 90
    common: 86400



